### ISSUE TITLE
Why shift the patch coordinates in '_lidar2image_preprocess'?

### ISSUE THREAD

**Issue by yutao98** [Haiyang-W/UniTR#10]
Hi, I'm confused about this operation in `_lidar2image_preprocess`. Why shift the coordinates of the initial patch? Does this cause a mismatch with the 2d coordinates projected from the radar coordinates?
https://github.com/Haiyang-W/UniTR/blob/60cd0093d3c94333cd9f8c7accede89a6af24c9d/pcdet/models/mm_backbone/unitr.py#L315

**Comment by nnnth** [comment]
Thanks for catching that detail. This is a confusion between x and y coordinates. 

The image size is (256, 704), and during coordinate mapping, we initially considered x corresponding to 704 and y corresponding to 256. However, in the `_lidar2image_preprocess` function and the variable `lidar2image_coords_zyx`, x actually corresponds to 256, and y corresponds to 704. Regarding the specific line of code you inquired about, the order of `multiview_coords` is bzyx, with `hw_shape=(32, 88)`. According to the correspondence just mentioned, the y column should be incremented by 88.

In this [line](https://github.com/Haiyang-W/UniTR/blob/60cd0093d3c94333cd9f8c7accede89a6af24c9d/pcdet/models/model_utils/unitr_utils.py#L322), we reordered the coordinates to adjust for this inconsistency between the x and y axes. Since these coordinates are only used to partition sets, it suffices for the order to remain consistent between `lidar2image_coords_bzyx` and `multiview_coords`.

The fundamental cause of the confusion lies in a confusion during the [initialization](https://github.com/Haiyang-W/UniTR/blob/60cd0093d3c94333cd9f8c7accede89a6af24c9d/pcdet/models/mm_backbone/unitr.py#L61) of `patch_coords`. The correspondence between the x and y axes involves intricate and nuanced details, and unfortunately, we did not address this after completing the experiments. We apologize for any confusion in this regard. Feel free to ask if you have any further questions.

**Comment by yutao98** [comment]
Thanks for quick reply! However, in the [initialization](https://github.com/Haiyang-W/UniTR/blob/60cd0093d3c94333cd9f8c7accede89a6af24c9d/pcdet/models/mm_backbone/unitr.py#L61) you mentioned, I notice that y do correspond to 88, and x corresponds to 32, which is consistent with the mapped coodinates `lidar2image_coords_zyx`, where each row is (unique_hit_view_id, y, x).

After checking the `map_lidar2image` function, I found that the key is [here](https://github.com/Haiyang-W/UniTR/blob/3f75dc1a362fe8f325dabd2e878ac57df2ab7323/pcdet/models/model_utils/unitr_utils.py#L278). This step keeps the points of the projection around the original image plane, which is why `sparse_shape` is 3×(32, 88), thus the coordinates of the original patch is needed to shift to the center of the `sparse_shape` in `_lidar2image_preprocess`. 

I confused the result of `torch.clamp(hit_points_2d, -1, 2) + 1` and `torch.clamp(hit_points_2d, 0, 3)`, that led to my initial question. If my understanding is not complete, please correct me.

**Comment by yutao98** [comment]
okay i missed that, and thanks for your patient reply and your nice work!
