### ISSUE TITLE
Hi Haiyang,

### ISSUE THREAD

**Issue by Sprinter1999** [Haiyang-W/UniTR#17]
I'm wondering if you have any plan to merge UniTR into mmdetection3d (via PR), which will broaden the influence of UniTR?

**Comment by Haiyang-W** [comment]
I am busy with other projects now. Maybe I will consider merging unitr into pcdet, because unitr is based on pcdet, but I don't have an exact timeline. Merging with mmdetection3d might take a bit more work for me. 
If you want to try merging into mmdetecion3d, I would also be very, very grateful. :)

**Comment by Sprinter1999** [comment]
Thank you haiyang. Recently I've conducted some experiments of UniTR and understood its main pipeline. It is fairly clear and easy-to-follow! Perhaps I'll consider merging it into mmdetection3d after cvpr rebuttal : ) Thank you again for your works!

**Comment by Haiyang-W** [comment]
Thanks very much. I hope this paper will be helpful to you. If you have any questions, I will try my best to help you solve them.

**Comment by Haiyang-W** [comment]
DSVT has been merged into [mmdetection3d](https://github.com/open-mmlab/mmdetection3d/tree/main/projects/DSVT), which may be helpful for UniTR mmdetection3d version. :)
