### ISSUE TITLE
How to Visualize Inference Results

### ISSUE THREAD

**Issue by xifen523** [Haiyang-W/UniTR#9]
How can I view my inference results once I have loaded the results using the pre-trained model?

**Comment by nnnth** [comment]
Our method is developed based on OpenPCDet, so you can refer to OpenPCDet's visualization [doc](https://github.com/open-mmlab/OpenPCDet/blob/master/docs/DEMO.md). However, since the original framework only supports point cloud input, some modifications are needed to input image data, which should be very similar to working with point clouds.
